### ISSUE TITLE
Wrong address mode chosen

### ISSUE THREAD

**Issue by armaray** [GrenDrake/ggasm#7]
Here a small test program:
==============
; include the glulx header file
include "glk.asm"

; set the stack size to 2048 bytes; this must be a multiple of 256
stackSize 2048

;Global variables:

bytesFixed mainwin            4

;Global Functions are put to ROM
toROM

; Function main( this )
function main 0
    setiosys 2 0
    copy 0 sp
    copy 3 sp
    copy 0 sp
    copy 0 sp
    copy 0 sp
    glk 35 5 mainwin
    copy mainwin sp
    glk 47 1 sp
    callf floyd_main 0
    return 0

; Function floyd_main
function floyd_main 0
    streamstr S0
    streamstr "Text output"

    return 0

endROM
;end of Global Functions

;Strings
string S0 "MyString"
==========

This compiles without error, here the symbols table:

00000104  String            S0
00000100  BuiltIn           _startOfRAM
0000006a  String            _string0
00000059  LocalFunction     floyd_main
00000028  LocalFunction     main
00000100  Data              mainwin

Correctly the functions are in ROM as specified, the variable mainwin (int) and the string S0 are in RAM as expected.

But when starting the compiled ulx the interpreter complains "Constant addressing mode in store operand"

Having a closer look to the generated code shows

glk 35 5 mainwin    8130 1103 23 05 0000 0000

So mainwin is considered to be a constant value instead of an address in RAM and value is simply 0 (int value)

Similar problems occur later for

callf floyd_main 0

and the streamstr statements.

The example basic.asm compiles without problem and runs in interpreter, so correct compilation can be assumed.

**Comment by GrenDrake** [comment]
This is actually two separate issues.

The first, when using a memory address as a storage operand, you need to use the \* operator to tell glulx that you want to use the contents of the address rather than the address itself, currently you're trying to store the result in the constant number 0x100 rather than at the memory address 0x100. So:

```
glk 35 5 *mainwin
```

The second issue, with `floyd_main`, is the result of a bug where labels were not being properly evaluated in the ROM area. This will be fixed in the newest version as soon as I push it.

Also, you may want to put larger code samples inside of code markup of some sort - see the markdown guide linked through the "Styling with Markdown is supported" text.
